### ISSUE TITLE
Version: v3.9.10.19 无法获取

### ISSUE THREAD

**Issue by lujihong** [git-jiadong/WeChatDBKey#1]

**Comment by git-jiadong** [comment]
@lujihong 

我测试了64bits的v3.9.10.19是可以正常获取的，如果你那边测试还是失败，可以附上你的日志

**Comment by lujihong** [comment]
PID: 15384
Version: v3.9.10.19
BaseAddr: 0x7FFE6E0D0000
DllSize: 103329792
BaseAddr: 0x7FFE6E0D0000
DllSize: 103329792
Is 64Bits: true
FilePath UNC\Mac\Home\Documents\WeChat Files\wxid_wueptyxlbvhv12
AcountName: wxid_wueptyxlbvhv12
DBKey:

**Comment by git-jiadong** [comment]
@lujihong 你需要wechat DLL的dump信息，才能分析出来。
直接发送出来可能会泄露你微信的信息，你可以加我vm：qq1174221722，我可以帮忙调试。

**Comment by lujihong** [comment]
加微信？还是qq?
